from __future__ import annotations

from typing import List, Optional


def _is_en(lang: Optional[str]) -> bool:
    return str(lang or "zh").lower().startswith("en")


def _tr(lang: Optional[str], zh: str, en: str) -> str:
    """按语言返回对应文案。"""
    return en if _is_en(lang) else zh


_TIER_LABELS_ZH = {"country": "国家", "city": "城市", "org": "机构"}
_TIER_LABELS_EN = {"country": "Country", "city": "City", "org": "Organization"}
_AFFIL_LABELS_ZH = {
    "affiliation_country": "国家",
    "affiliation_org": "机构",
    "affiliation_city": "城市",
}
_AFFIL_LABELS_EN = {
    "affiliation_country": "Country",
    "affiliation_org": "Organization",
    "affiliation_city": "City",
}


def _tier_label(tier: str, lang: Optional[str]) -> str:
    """返回层级（国家/城市/机构，含 affiliation_ 前缀）在当前语言下的标签。"""
    zh = {**_TIER_LABELS_ZH, **_AFFIL_LABELS_ZH}
    en = {**_TIER_LABELS_EN, **_AFFIL_LABELS_EN}
    return (en if _is_en(lang) else zh).get(tier, tier)


# 各校验函数返回的中文「问题描述」在日志里展示时的英文映射
_ISSUE_LABELS_EN = {
    "经纬度为空": "empty coordinates",
    "经纬度为0": "zero coordinates",
    "经纬度越界": "coordinates out of range",
    "纬度越界": "latitude out of range",
    "经度越界": "longitude out of range",
    "国家/地区为空": "empty country/region",
    "机构为空": "empty organization",
    "机构名为空": "empty organization name",
    "城市为空": "empty city",
    "城市详情为空": "empty city detail",
}


def _tr_issues(issues: List[str], lang: Optional[str]) -> List[str]:
    """把校验函数返回的中文问题描述按语言翻译，供日志展示。
    形如 "Country 为空"（name_key 为英文）走后缀替换。"""
    if not _is_en(lang):
        return list(issues)
    out = []
    for s in issues:
        s = str(s)
        if s in _ISSUE_LABELS_EN:
            out.append(_ISSUE_LABELS_EN[s])
        elif s.endswith(" 为空"):
            out.append(f"{s[:-3].strip()} empty")
        elif s.endswith("为空"):
            out.append(f"{s[:-2].strip()} empty")
        else:
            out.append(s)
    return out


def _join_issues(issues: List[str], lang: Optional[str], n: int) -> str:
    """按语言翻译并拼接前 n 个问题描述。"""
    return ", ".join(_tr_issues(issues, lang)[:n])


# >>> AUTO-GENERATED ZH CATALOG
# Do not edit by hand; regenerated by _migrate_i18n.py
# Access: from core.i18n import ZH; ZH.S_xxxx

class ZH:
    """Centralized Chinese UI/log string literals (non-docstring, non-triple-quoted)."""

    S_0045f05cd5 = "数据中不含 "
    S_02b44ef924 = " 条地址记录"
    S_03df0992fa = " 个模型 | 超时 "
    S_04b77d7006 = "未找到机构或国家列: "
    S_0509d65bbd = "[DEBUG] 开始转换数值字段为int类型..."
    S_053d5fdbc9 = "═══ 阶段 3：C3 批量 Nominatim 补救（"
    S_08150aba99 = " 个地址已尝试全部模型仍不完整，进入最终阶段"
    S_0875f836a0 = " 个地址需修复，但未配置可用 AI 模型，跳过"
    S_08e7b77ea3 = "最终阶段完成：修复 "
    S_098b266908 = " 个，跳过 AI 调用"
    S_09d8095542 = "不支持的文件名: "
    S_0bf60b32f9 = "数量"
    S_0bfed077e9 = "] 最终阶段："
    S_0e4abc04ea = "[DEBUG] 数据版本: "
    S_10f13709c0 = "[DEBUG] RecordCollection 创建成功，记录数: "
    S_112dd14360 = " 地址已按分号分割并去重："
    S_12e6cd7bf4 = "纬度越界"
    S_1304f43377 = "    ✓ 最终修复 ["
    S_13bdf5c2bc = "无法识别文件列结构，列名: "
    S_152dad9f20 = "Affiliation 类型数据不支持质量检查"
    S_1622dc9b6b = "未知"
    S_18f7bd26e3 = "   ✗ 最终失败 ["
    S_1906446269 = "[DEBUG] 使用缓存: "
    S_19e9a630de = "[DEBUG] 开始创建 RecordCollection..."
    S_1a2b0de102 = "经纬度为空"
    S_1a48e09bee = "  第 "
    S_1be16a5594 = "] 没有可解析的名称"
    S_1cec709824 = "[DEBUG] 已处理 "
    S_1d4c92c776 = "[WARN] 缺少文件，跳过: "
    S_1e700221f9 = "[INFO] CSV 目录: "
    S_1fce799168 = "启动 "
    S_20c109e4a8 = " | 剔除无效 "
    S_20c302ef11 = "✅ 全部解析完成 | 国家/机构/城市 均已完成 | 成功率 "
    S_218030a5e8 = "[DEBUG] 国家名称清洗完成"
    S_218dc60913 = "[DEBUG] DataFrame 列名: "
    S_2560b304e6 = "地区"
    S_26245c87e1 = "最终阶段：所有地址均已完整解析，无需修复"
    S_276eac722d = "[DEBUG] 开始清洗C1字段国家名称..."
    S_29062f71e8 = "C3 不支持分层解析，请使用统一解析"
    S_2991832520 = "无效的层级: "
    S_2a2eeeba05 = " 个需修复，但未配置 AI，跳过"
    S_2c25baff2d = "启动 affiliation 全量解析 | "
    S_2cfdfc96a7 = "   第 "
    S_2df8a1e714 = "  ── 第 "
    S_2fdf3b2995 = "  🗃 已跳过固定参考库，全部交由大模型解析"
    S_307fa0eb3b = "全部 Session 已清除"
    S_31c585a23a = "🗃 已跳过固定参考库，全部交由大模型解析（全量）"
    S_31d4879f0d = "   本轮无新进展（"
    S_33936daaca = " 条记录时发生 IndexError:"
    S_3394943a05 = "═══ 阶段 2：最终修复（不完整/0坐标地址） ═══"
    S_33f7cbbf8b = " 个地址经最终阶段后仍不完整，已标记为 pending"
    S_3435494fd2 = "] 全部命中缓存，秒完成！"
    S_34b18ec132 = "城市为空"
    S_353d620c12 = "── 第 "
    S_38040c8dfb = "] 全部命中参考库，秒完成！"
    S_38ae2fd0ea = "⚠ 仍有 "
    S_39c7b31e48 = "国家/地区"
    S_3b2e601f56 = " 轮完成：成功 "
    S_3b5dabe8ba = "] ⏹ 已停止 | "
    S_3b67d66108 = "  🗃 已跳过固定参考库，全部交由大模型重算"
    S_3be5fe67b8 = " 轮：处理 "
    S_3c0bb5c541 = "继续重试..."
    S_3d18ca01dd = "经度"
    S_3e4ff6c5ce = "，待重试 "
    S_3e70c2d15e = "文件 "
    S_3f5552e0f3 = "s/次"
    S_4062627ab9 = "模型: "
    S_41461fa09f = "频次"
    S_44850b044b = " 个模型"
    S_45b2d61cd6 = "✅ 全部完成！共 "
    S_46edf8b789 = "未选择文件"
    S_48589c5729 = "   最终阶段失败 ["
    S_49b3810efc = " 解析"
    S_4a528581a6 = "文件不存在: "
    S_4d15d14051 = "] 超时跳过: "
    S_4f87bfbbc5 = ": 总 "
    S_501555462c = " | 有效 "
    S_50550ece75 = "最终阶段：有 "
    S_5095e98c51 = " 不存在"
    S_510a0c262b = "[DEBUG] 数值字段转换完成"
    S_532e60f345 = "[ERROR] 没有任何有效数据，终止。"
    S_5380e4315a = "文件为空: "
    S_53d2ea9fcb = " 条记录"
    S_556be01584 = "🔗 Nominatim 编码成功: "
    S_57730c7510 = "⏹ 正在停止，等待当前请求完成..."
    S_59d76cf338 = " 层"
    S_5b1016bef8 = "    ✗ 最终未通过 ["
    S_5c96b9c187 = " | 写入 "
    S_5d2af7d2ae = " 个"
    S_5e08e1c379 = "），使用 "
    S_5ed37cb9e6 = "[DEBUG] 最终 DataFrame 形状: "
    S_610bbf8e78 = "，失败(待重试) "
    S_6115ab046e = "示例数据为空"
    S_614b8788f4 = "未找到有效地址数据: "
    S_62e13cc927 = " 个需修复，选用主轮成功率最高的模型 ["
    S_63636580bf = "[DEBUG] DataFrame 构建成功，行数: "
    S_6437879a45 = "demoData 目录不存在"
    S_679f8f1fe8 = "当前 Session 不是 affiliation 类型"
    S_689581b610 = "] 错误: "
    S_6acaee71fe = "纬度"
    S_6c308de674 = "⏹ 已停止 | 已完成 "
    S_6d1f6b1a29 = "已向所有层级发送停止信号"
    S_6dcbb0970a = " 条记录时发生错误:"
    S_6f5ecb4859 = "[DEBUG] 开始构建 DataFrame..."
    S_6f7f1b61f6 = "🗃 参考库命中 "
    S_7048c7a378 = "示例数据文件不存在: "
    S_7085e8f542 = " 为空"
    S_72106d8e57 = "已启动 "
    S_73f01561e4 = " 个机构，跳过 AI 调用"
    S_7449367fa2 = "错误: "
    S_74a9dc6291 = "   最终阶段未通过 ["
    S_74f0a70b5e = "[INFO] 目标数据库: "
    S_7650487a87 = "地址"
    S_77d386365b = " 个唯一名称 | "
    S_7a8e552018 = "[ERROR] 错误信息: "
    S_7cdc1fa367 = "tier 必须是 country / city / org 之一"
    S_7d55c093d9 = " 个地址已尝试全部模型，进入最终阶段"
    S_7d8d95d685 = "无解析任务"
    S_7e5c223dfb = "文件解析失败 ["
    S_8086bdef9b = "解析任务已启动"
    S_81a686f1af = " 个地址 ──"
    S_83d996b971 = "未找到有效的机构或国家数据"
    S_84e5ead8ee = "   文件大小: "
    S_8604bedd31 = "Session 已清除"
    S_866306f543 = "[DEBUG] 记录遍历完成，共处理 "
    S_87d741df7a = "模式: 跳过固定参考库，强制大模型重算"
    S_887351b33b = "国家/地区为空"
    S_89339c2bdc = "[DEBUG] 开始遍历记录，总数: "
    S_894dfcd42b = "机构名称"
    S_8b022af1f4 = "%）单模型重试，超时 "
    S_8bc45d6415 = "Nominatim 补救完成：成功更新 "
    S_8d9a243412 = " 个模型..."
    S_8de362b496 = " 个唯一地址"
    S_8e5767e2c0 = " 的统一数据，请先调用 /api/geo/parse-c1?field=C3 完成解析"
    S_8f351ee448 = "[DEBUG] DataFrame 创建完成，形状: "
    S_8fea440ed1 = "\n[DONE] 参考库构建完成"
    S_924f26926c = "无法识别文件编码: "
    S_92740e4266 = "[ERROR] 错误类型: "
    S_93e3430d8a = "[DEBUG] 开始加载目录: "
    S_9449fc6faa = "[DEBUG] _build_dataframe: 记录集合大小 = "
    S_948623584a = " 条"
    S_970f0e9c98 = "   ✓ 最终修复 ["
    S_97cb1b6512 = "\n[ERROR] 加载目录时发生错误:"
    S_987e97f4d0 = "，累计 "
    S_99b09fd190 = " 条地址记录 → "
    S_99c6262c4f = "WoS 解析失败: "
    S_99da6f1e75 = " 已展开地址记录：原始 "
    S_9a17f1fc99 = "   记录总数: "
    S_9e5417e701 = "[INFO] 去重后唯一名称（小写 key）: "
    S_a06bfbaa06 = "[ERROR] 记录内容: "
    S_a20759f68f = "经纬度为0"
    S_a3682655b9 = "   分类统计: "
    S_a535de215b = "Session 不存在"
    S_a78496f6ab = "\n[ERROR] _build_dataframe 发生错误:"
    S_a865e2e99a = "启动解析（字段: "
    S_a8ed9d2016 = "放弃剩余，进入最终阶段"
    S_a9d3a66867 = "请先执行 "
    S_aa048795c0 = "] 结果不完整，转其它模型: "
    S_aabffa5576 = " 分层解析"
    S_ab28765753 = "字段: "
    S_ac1b29a02d = "篇数"
    S_ad29083184 = " 个地址"
    S_ada63452ab = "] ✅ 完成！成功 "
    S_aebadf691f = "[DEBUG] 字段衍生完成，最终形状: "
    S_aeda4a320d = "] 不完整: "
    S_b08afc8493 = "，必须是 country / city / org 之一"
    S_b09e05d890 = " 轮 + 最终阶段 | 成功 "
    S_b0c5ae0680 = "最终阶段：用户已停止，跳过"
    S_b173832080 = " 轮 | 成功 "
    S_b219484375 = "═══ 阶段 3：C3 无需 Nominatim 补救 ═══"
    S_b24791a1db = "解析（字段: "
    S_b248610462 = "[DEBUG] 开始字段衍生..."
    S_b31c4aee47 = "经纬度越界"
    S_b4e7c25ad8 = "未找到有效的 affiliation 文件"
    S_b5f24efa6c = " 个唯一地址 | "
    S_b724de7f8f = "机构名为空"
    S_b73d9d3bc2 = "记录数"
    S_b77053aabc = "机构"
    S_b974fd0d1a = "[DEBUG] 目录存在: "
    S_b9b3df78b5 = "城市详情为空"
    S_ba3f36d69c = "无法解析文件: "
    S_bdc3ef7cc5 = " | 成功率 "
    S_bf1ad3f2d1 = "。可选值: "
    S_bf380ba31c = "无法获取模型列表，请检查 API 地址和 Key。已尝试: "
    S_c113c60734 = " 个地址需修复，选用主轮成功率最高的模型 ["
    S_c284a8c31f = "模式: 优先使用固定参考库（只读，不写回）"
    S_c3efb6223e = " 条 → 地址记录 "
    S_c4c875f2d1 = " | 跳过缓存"
    S_c55621865c = "无运行中的解析任务"
    S_c7a844ef42 = "   ✓ 最终修复成功 ["
    S_c8c22776b8 = "] 阶段 2：最终修复 ═══"
    S_c9085a5de6 = "既有解析结果已清除，请重新执行地理解析"
    S_caad6cfd1d = "  🗃 参考库命中 "
    S_cbd5c22fa1 = "C3 全部命中参考库，秒完成！"
    S_ccfbe706fe = "单位名称"
    S_d079564cea = "，待补全 "
    S_d07a44409e = "] 阶段 1：主轮多模型快速解析"
    S_d1a8c34329 = "] 跳过("
    S_d237338231 = "] 启动 | 共 "
    S_d2d3fe41a7 = "Affiliation 类型数据不支持去重"
    S_d3f1c641d3 = "[ERROR] 完整堆栈跟踪:"
    S_d5a69aa0c9 = "分层解析 ["
    S_d7a4491ea4 = "至少需要选择一个层级"
    S_d81bb206a8 = "无"
    S_d8ac209b72 = "解析完成！共 "
    S_d8f81ea417 = "本地地址模式不支持混合上传其他格式文件: "
    S_d90dbff5fc = "[DEBUG] 调用 makeDict()..."
    S_d97d01f9b7 = "] 所有名称均已完整解析"
    S_dbcdc2ee01 = "至少需要一个模型配置"
    S_dd490b1053 = "   ✗ 最终未通过 ["
    S_dd81478f85 = "经度越界"
    S_de44ab745e = "] 阶段 2：最终修复"
    S_de8b013ca7 = "    ✗ 最终失败 ["
    S_dfdac5a4d6 = "] 无数据，跳过"
    S_e09991d26d = " 条记录 | "
    S_e14ca9c88d = " 个名称 ──"
    S_e3fd360e5f = "] 超时: "
    S_e4c855fdeb = "coord_type 必须是 normalized / geo / none 之一"
    S_e5cb77dc43 = " 的数据，请先调用 /api/geo/parse-tier 解析 "
    S_e8e0063a99 = "] 修复 "
    S_e9eda06f8b = "停止信号已发送"
    S_e9fbbc88d6 = "Anthropic 模型列表获取失败: "
    S_ea0eaf03af = "解析：字段 "
    S_ea157063a0 = "该 session 尚未解析 field="
    S_ea9e410d45 = "] 阶段 1：主轮多模型解析 ═══"
    S_ed66551897 = "[DEBUG] 创建最终 DataFrame..."
    S_ee3f5585b1 = "国家"
    S_ee785b44db = "═══ 阶段 1：主轮多模型快速解析 ═══"
    S_f059508497 = " 个，仍未完成 "
    S_f136476580 = " 条） ═══"
    S_f204cee7ee = "示例数据解析失败: "
    S_f25692c9cb = "字段 "
    S_f2996845b6 = "单位"
    S_f405767eca = " 个层级解析："
    S_f4878dd08a = "最终阶段："
    S_f61f4cf6d0 = "暂无"
    S_f6d7e82e7e = "国别"
    S_fa972a917d = " 字段"
    S_fac6485384 = " | 共 "
    S_fb72d76935 = "] | 字段: "
    S_fd5bf370e1 = "\n[ERROR] 处理第 "
    S_fd89e9bd29 = "，请确认是 TSV/CSV 格式"
    S_fe0c993578 = " 没有可解析的地址"
    S_ff59e30102 = "机构为空"
    S_ffde352c58 = "[DEBUG] makeDict() 完成，类型: "
    S_err_load_dir = "\n[ERROR] 加载目录时发生错误:"
    S_err_build_df = "\n[ERROR] _build_dataframe 发生错误:"
    S_need_fix = " 个需修复，"
    S_need_fix_addr = " 个地址需修复，"
    S_cn_comma = "，"
    S_pick_best_model = "选用主轮成功率最高的模型 ["
    S_fail_retry = "失败(待重试) "
    S_paren_rate = "（"
    S_cn_comma_close = "），"


def zh(key: str) -> str:
    """Lookup by key name, e.g. zh("S_ab12cd")."""
    return getattr(ZH, key)
# <<< AUTO-GENERATED ZH CATALOG
